data:
  n_signal: 65536
  preprocessed: null
  sr: 16000
  wav: null

model:
  bias: true
  capacity: 64
  d_capacity: 16
  d_multiplier: 4
  d_n_layers: 4
  data_size: 16
  latent_size: 128
  no_latency: false
  noise_bands: 5
  noise_ratios:
  - 4
  - 4
  - 4
  ratios:
  - 4
  - 4
  - 4
  - 2
  use_noise: true
  loud_stride: 1
  batch: 8
  ckpt: null
  cropped_latent_size: 0
  feature_match: true
  max_kl: 0.1
  max_steps: 3000000
  min_kl: 0.1
  mode: hinge
  models_dir: null
  name: null
  warmup: 1000000
