data:
  data_name: null
  descriptors:
  - centroid
  # - rms 
  # - zcr 
  # - sharpness 
  # - booming
  n_signal: 65536
  preprocessed: null
  sr: 16000
  wav: null
fader:
  clip_grad_norm: 0
  initialize: 0
  num_classes: 16
  num_lat_dis_layers: 2
  rave_ckpt: null
rave:
  bias: true
  capacity: 64
  cropped_latent_size: 0
  d_capacity: 16
  d_multiplier: 4
  d_n_layers: 4
  data_size: 8
  feature_match: true
  latent_size: 128
  loud_stride: 1
  max_kl: 0.1
  min_kl: 0.1
  mode: hinge
  no_latency: false
  noise_bands: 5
  noise_ratios:
  - 4
  - 4
  - 4
  ratios:
  - 4
  - 4
  - 4
  - 2
  use_noise: true
  warmup: 300000
train:
  batch: 64
  beta_delay: 1
  beta_inf: 0.1
  ckpt: null
  display_step: 100
  lambda_delay: 1
  lambda_inf: 0.1
  max_steps: 600000
  models_dir: null
  n_lat_dis: 1
  name: null
  val_check: 5
